package com.im.my.protocol.command;

public interface Command
{
    Byte LOGIN_REQUEST = 1;
    Byte LOGIN_RESPONSE = 2;

    Byte MESSAGE_REQUEST = 3;
    Byte MESSAGE_RESPONSE = 4;

    Byte LOGOUT_REQUEST = 5;
    Byte LOGOUT_RESPONSE = 6;

    Byte CREATE_GROUP_REQUEST = 7;
    Byte CREATE_GROUP_RESPONSE = 8;

    Byte LIST_GROUP_MEMBERS_REQUEST = 9;
    Byte LIST_GROUP_MEMBERS_RESPONSE = 10;

    Byte JOIN_GROUP_REQUEST = 11;
    Byte JOIN_GROUP_RESPONSE = 12;

    Byte QUIT_GROUP_REQUEST = 13;
    Byte QUIT_GROUP_RESPONSE = 14;

    Byte SEND_MESSAGE_TO_GROUP_REQUEST=15;
    Byte SEND_MESSAGE_TO_GROUP_RESPONSE=16;

    Byte HEAT_BEAT_REQUEST=17;
    Byte HEAT_BEAT_RESPONSE=18;

    Byte SENSOR_REQUEST = 19;
    Byte SENSOR_RESPONSE=20;

    Byte REGISTER_REQUEST=21;
    Byte REGISTER_RESPONSE=22;

    Byte ADD_FRIEND_REQUEST=23;
    Byte ADD_FRIEND_RESPONSE=24;

    Byte DELETE_FRIEND_REQUEST=25;
    Byte DELETE_FRIEND_RESPONSE=26;

    Byte SHOW_FRIENDS_LIST_REQUEST=27;
    Byte SHOW_FRIENDS_LIST_RESPONSE=28;

    Byte SHOW_GROUP_LIST_REQUEST=29;
    Byte SHOW_GROUP_LIST_RESPONSE=30;
}
